version: "3.8"

services:
  ollama-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_URL=http://ollama:11434
    restart: always
    depends_on:
      - ollama
    networks:
      - ollama-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    restart: always
    entrypoint: ["/bin/sh", "-c", "ollama start && ollama run llama3:8b"]
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
