version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      resources:
        limits:
          cpus: "2.5"
          memory: 10G
        reservations:
          cpus: "1.5"
          memory: 8G
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    entrypoint: ["/root/retry.sh"]

volumes:
  ollama:
